// Content pipelines: load what a prompt needs from the database and the Source Corpus, build the
// Generation request, and persist what must be persisted (Notion Outline, quizzes, replaced
// questions). Callers choose how to run a request: `service.generate` or `service.pregenerate`.
import type { Corpus } from '../corpus'
import type { Database } from '../db'
import {
  createQuiz,
  getQuestion,
  getQuiz,
  listQuestionHistory,
  replaceQuestion
} from '../db/repositories/assessment'
import {
  createNotions,
  getNotion,
  getTopic,
  listNotionsByTopic
} from '../db/repositories/learningContent'
import type { Notion, Question, Quiz, Topic } from '../db/types'
import type { GenerationPriority, Json } from '../../shared/generation'
import {
  buildLessonGeneration,
  buildNotionOutlineGeneration,
  buildQuizGeneration,
  buildRemediationLessonGeneration,
  questionBody,
  type GroundingInput,
  type NotionBrief,
  type PromptBuild,
  type QuizContent,
  type QuizOptions,
  type RemediationOptions,
  type TopicBrief
} from './prompts'
import type { GenerationRequest, GenerationResult, GenerationService } from './service'

export interface PipelineDeps {
  db: Database
  service: GenerationService
  corpus: Corpus
}

export interface RunOptions {
  priority?: GenerationPriority
  signal?: AbortSignal
}

/** Corpus version of ungrounded content: it does not change with the primer. */
const UNGROUNDED = 'ungrounded'

/** Enough to take every sub-topic of the largest primer topic. */
const MAX_EXCERPTS = 50

function requireTopic(db: Database, topicId: number): Topic {
  const topic = getTopic(db, topicId)
  if (!topic) throw new Error(`Topic ${topicId} does not exist.`)
  return topic
}

const topicBrief = (topic: Topic): TopicBrief => ({
  slug: topic.slug,
  title: topic.title,
  inFoundationsModule: topic.inFoundationsModule
})

/** The topic's section and its sub-topics; none in the Foundations Module (ungrounded). */
export function topicGrounding(corpus: Corpus, topic: Topic): GroundingInput {
  if (topic.inFoundationsModule) return { excerpts: [], corpusVersion: UNGROUNDED }
  if (!topic.sourceSection || !corpus.getSection(topic.sourceSection)) {
    throw new Error(`Topic ${topic.slug} has no Source Corpus section to be grounded on.`)
  }
  return {
    excerpts: corpus.findExcerpts({ sectionIds: [topic.sourceSection], limit: MAX_EXCERPTS }),
    corpusVersion: corpus.data.metadata.commitSha
  }
}

/** Exactly the sections a notion was outlined from (a topic id does not pull its sub-topics). */
export function notionGrounding(corpus: Corpus, notion: NotionBrief): GroundingInput {
  if (notion.sourceSections.length === 0) return { excerpts: [], corpusVersion: UNGROUNDED }
  const ids = new Set(notion.sourceSections)
  return {
    excerpts: corpus
      .findExcerpts({ sectionIds: [...ids], limit: MAX_EXCERPTS })
      .filter((excerpt) => ids.has(excerpt.sectionId)),
    corpusVersion: corpus.data.metadata.commitSha
  }
}

const toRequest = <T extends Json>(
  build: PromptBuild<T>,
  options: RunOptions
): GenerationRequest<T> => ({
  kind: build.kind,
  input: build.input,
  prompt: build.prompt,
  schema: build.schema,
  groundedSourceSections: build.groundedSourceSections,
  priority: options.priority,
  signal: options.signal
})

const outlinesInFlight = new WeakMap<Database, Map<number, Promise<Notion[]>>>()

/**
 * The topic's notions. Generated once (one Generation) and stored in the `notions` table, which
 * acts as the outline's cache: notion ids are referenced by question tags and attempts, so an
 * outline is never regenerated by a prompt version bump. Concurrent calls share one Generation.
 */
export function ensureNotionOutline(
  deps: PipelineDeps,
  topicId: number,
  options: RunOptions = {}
): Promise<Notion[]> {
  const existing = listNotionsByTopic(deps.db, topicId)
  if (existing.length > 0) return Promise.resolve(existing)

  let inFlight = outlinesInFlight.get(deps.db)
  if (!inFlight) outlinesInFlight.set(deps.db, (inFlight = new Map()))
  const pending = inFlight.get(topicId)
  if (pending) return pending

  const run = (async () => {
    const topic = requireTopic(deps.db, topicId)
    const build = buildNotionOutlineGeneration(
      topicBrief(topic),
      topicGrounding(deps.corpus, topic)
    )
    const { content } = await deps.service.generate(toRequest(build, options)).result
    return deps.db.transaction(() => {
      const stored = listNotionsByTopic(deps.db, topicId)
      if (stored.length > 0) return stored
      return createNotions(
        deps.db,
        content.notions.map((notion) => ({ topicId, ...notion }))
      )
    })
  })()
  inFlight.set(topicId, run)
  const forget = () => inFlight.delete(topicId)
  run.then(forget, forget)
  return run
}

/** Streamed lesson on a topic (its Notion Outline is generated first if needed). */
export async function prepareLesson(
  deps: PipelineDeps,
  topicId: number,
  options: RunOptions = {}
): Promise<GenerationRequest<string>> {
  const topic = requireTopic(deps.db, topicId)
  const notions = await ensureNotionOutline(deps, topicId, options)
  const build = buildLessonGeneration(
    topicBrief(topic),
    notions,
    topicGrounding(deps.corpus, topic)
  )
  return toRequest(build, options)
}

/** Quiz on a topic; options cover the Mastery Loop rounds (focus and reminder notions). */
export async function prepareQuiz(
  deps: PipelineDeps,
  topicId: number,
  quiz: QuizOptions = {},
  options: RunOptions = {}
): Promise<GenerationRequest<QuizContent>> {
  const topic = requireTopic(deps.db, topicId)
  const notions = await ensureNotionOutline(deps, topicId, options)
  const build = buildQuizGeneration(
    topicBrief(topic),
    notions,
    topicGrounding(deps.corpus, topic),
    quiz
  )
  return toRequest(build, options)
}

/** Streamed Remediation Lesson on one notion, grounded on that notion's sections. */
export function prepareRemediationLesson(
  deps: PipelineDeps,
  notionId: number,
  remediation: RemediationOptions,
  options: RunOptions = {}
): GenerationRequest<string> {
  const notion = getNotion(deps.db, notionId)
  if (!notion) throw new Error(`Notion ${notionId} does not exist.`)
  const topic = requireTopic(deps.db, notion.topicId)
  const build = buildRemediationLessonGeneration(
    topicBrief(topic),
    notion,
    notionGrounding(deps.corpus, notion),
    remediation
  )
  return toRequest(build, options)
}

/** Stores a generated quiz with its questions, tags mapped from notion slugs to ids. */
export function saveQuiz(
  db: Database,
  topicId: number,
  result: Pick<
    GenerationResult<QuizContent>,
    'content' | 'grounded' | 'sourceSections' | 'cacheKey'
  >
): Quiz {
  const idBySlug = new Map(listNotionsByTopic(db, topicId).map((n) => [n.slug, n.id]))
  return createQuiz(db, {
    topicId,
    grounded: result.grounded,
    sourceSections: result.sourceSections,
    contentCacheKey: result.cacheKey,
    questions: result.content.questions.map((question, position) => ({
      position,
      type: question.type,
      prompt: question.prompt,
      body: questionBody(question),
      notionIds: question.notions.map((slug) => {
        const id = idBySlug.get(slug)
        if (id === undefined) throw new Error(`Unknown notion "${slug}" in a generated quiz.`)
        return id
      })
    }))
  })
}

/**
 * Generates a replacement for a flagged question (see `flagQuestion`) and swaps it in: same
 * type, same notion tags, same position; the flagged question stays in the quiz history. The
 * new question must differ from every question the quiz ever had.
 */
export async function regenerateQuestion(
  deps: PipelineDeps,
  questionId: number,
  options: RunOptions = {}
): Promise<Question> {
  const flagged = getQuestion(deps.db, questionId)
  if (!flagged) throw new Error(`Question ${questionId} does not exist.`)
  if (flagged.flaggedAt === null) throw new Error(`Question ${questionId} is not flagged.`)
  if (flagged.replacedByQuestionId !== null) {
    throw new Error(`Question ${questionId} was already replaced.`)
  }
  const quiz = getQuiz(deps.db, flagged.quizId)!
  const topic = requireTopic(deps.db, quiz.topicId)
  const notions = listNotionsByTopic(deps.db, topic.id)
  const tagged = notions.filter((notion) => flagged.notionIds.includes(notion.id))

  const grounding: GroundingInput = quiz.grounded
    ? topicGrounding(deps.corpus, topic)
    : { excerpts: [], corpusVersion: UNGROUNDED }
  const build = buildQuizGeneration(topicBrief(topic), notions, grounding, {
    count: 1,
    types: [flagged.type],
    focusNotions: tagged.map((notion) => notion.slug),
    avoidPrompts: listQuestionHistory(deps.db, quiz.id).map((question) => question.prompt),
    replaces: { prompt: flagged.prompt, reason: flagged.flagReason }
  })
  const { content } = await deps.service.generate(toRequest(build, options)).result
  const replacement = content.questions[0]!
  return replaceQuestion(deps.db, questionId, {
    type: replacement.type,
    prompt: replacement.prompt,
    body: questionBody(replacement),
    // Same tags as the flagged question by construction, whatever the model tagged.
    notionIds: flagged.notionIds
  })
}
